import Link from "next/link";

export default function ThankYouPage({ searchParams }: { searchParams?: { orderId?: string } }) {
  return (
    <main className="min-h-screen bg-[#FCF5EE] px-6 py-16 text-[#0F2540] sm:px-10">
      <div className="mx-auto flex max-w-3xl flex-col items-center rounded-[2rem] border border-[#e3dccb] bg-white px-6 py-12 text-center shadow-[0_10px_40px_rgba(0,0,0,0.06)] sm:px-10">
        <span className="inline-flex rounded-full bg-[#3a988a]/10 px-4 py-2 text-sm font-semibold text-[#3a988a]">
          Order placed successfully
        </span>
        <h1 className="mt-6 text-4xl font-bold sm:text-5xl" style={{ fontFamily: "'Baloo 2', cursive" }}>
          Thank you for your order
        </h1>
        <p className="mt-4 max-w-xl text-base leading-7 text-[#7A6F5D]">
          Your order has been received and is being prepared. We’ll reach out soon with the next steps.
        </p>
        {searchParams?.orderId ? (
          <p className="mt-4 rounded-full bg-[#f8f5ef] px-4 py-2 text-sm font-medium text-[#2F2A22]">
            Order ID: {searchParams.orderId}
          </p>
        ) : null}
        <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
          <Link href="/" className="rounded-full bg-[#ff7d6b] px-6 py-3 text-sm font-semibold text-white">
            Continue Shopping
          </Link>
          <Link href="/cart" className="rounded-full border border-[#e3dccb] px-6 py-3 text-sm font-semibold text-[#0F2540]">
            View Cart
          </Link>
        </div>
      </div>
    </main>
  );
}

export interface Review {
  id: number;
  name: string;
  city: string;
  rating: number;
  review: string;
}

export const reviews: Review[] = [
  { id: 1, name: "Sana Abbasi", city: "Rawalpindi", rating: 5, review: "Absolutely loved the eid collection outfit I ordered for my kid. Worth every rupee spent." },
  { id: 2, name: "Zoya Sheikh", city: "Multan", rating: 4, review: "the printed t-shirt pack is good value for money, nothing extraordinary but does the job. Would order again but hoping for faster delivery next time." },
  { id: 3, name: "Farwa Javed", city: "Sargodha", rating: 4, review: "This is my third order from Just Kiddin' and the pastel abaya set was the best yet. Will definitely order again soon." },
  { id: 4, name: "Shaista Bajwa", city: "Multan", rating: 5, review: "Stitching on the pastel abaya set is really neat, no loose threads at all. Five stars from me and my little one." },
  { id: 5, name: "Wardah Cheema", city: "Gujrat", rating: 4, review: "the printed t-shirt pack exceeded my expectations, honestly. Customer service was also very helpful throughout." },
  { id: 6, name: "Aqsa Warraich", city: "Sialkot", rating: 5, review: "Received the striped hoodie earlier than expected, packaging was neat too. Already planning my next order." },
  { id: 7, name: "Hafsa Raza", city: "Sargodha", rating: 5, review: "My son looks adorable in the eid collection outfit, so happy with the purchase. Already planning my next order." },
  { id: 8, name: "Abdullah Rashid", city: "Multan", rating: 4, review: "This is my third order from Just Kiddin' and the winter fleece jacket was the best yet. Customer service was also very helpful throughout." },
  { id: 9, name: "Aftab Siddiqui", city: "Rawalpindi", rating: 5, review: "Received the girls frock earlier than expected, packaging was neat too. Five stars from me and my little one." },
  { id: 10, name: "Hassan Warraich", city: "Gujrat", rating: 5, review: "Received the printed t-shirt pack earlier than expected, packaging was neat too. Highly recommend to all the moms out there." },
  { id: 11, name: "Alishba Qureshi", city: "Sialkot", rating: 3, review: "Happy with the corduroy pants overall, just wish there were more color options. Customer support responded a bit late but resolved my issue." },
  { id: 12, name: "Nadia Hussain", city: "Gujranwala", rating: 4, review: "Absolutely loved the cotton kurta set I ordered for my kid. Customer service was also very helpful throughout." },
  { id: 13, name: "Faizan Aslam", city: "Lahore", rating: 4, review: "Fabric of the boys polo shirts is comfortable, packaging could be better though. Customer support responded a bit late but resolved my issue." },
  { id: 14, name: "Amna Niazi", city: "Islamabad", rating: 5, review: "My son looks adorable in the printed t-shirt pack, so happy with the purchase. Customer service was also very helpful throughout." },
  { id: 15, name: "Tayyab Dogar", city: "Faisalabad", rating: 4, review: "My daughter can't stop wearing the corduroy pants, she loves it so much. Just Kiddin' has become our go to brand now." },
  { id: 16, name: "Rizwan Sheikh", city: "Sialkot", rating: 5, review: "The fabric quality on the floral summer dress is top notch, very soft on the skin. Five stars from me and my little one." },
  { id: 17, name: "Basit Iqbal", city: "Rawalpindi", rating: 4, review: "the school uniform bundle is nice but the size ran slightly small for my son. Would recommend with slight reservations about sizing." },
  { id: 18, name: "Sidra Khan", city: "Lahore", rating: 4, review: "Ordered the corduroy pants and the quality is amazing for the price. Customer service was also very helpful throughout." },
  { id: 19, name: "Mehak Butt", city: "Rawalpindi", rating: 5, review: "Stitching on the cotton kurta set is really neat, no loose threads at all. Highly recommend to all the moms out there." },
  { id: 20, name: "Sameer Rashid", city: "Karachi", rating: 5, review: "Received the striped hoodie earlier than expected, packaging was neat too. Delivery to Karachi was quick too." },
  { id: 21, name: "Rizwan Kiani", city: "Sargodha", rating: 5, review: "My son looks adorable in the cargo shorts set, so happy with the purchase. Delivery to Sargodha was quick too." },
  { id: 22, name: "Bilal Raza", city: "Sialkot", rating: 5, review: "Ordered the denim dungarees and the quality is amazing for the price. Colors were exactly as shown on the website." },
  { id: 23, name: "Sameer Niazi", city: "Rawalpindi", rating: 4, review: "the printed t-shirt pack exceeded my expectations, honestly. Just Kiddin' has become our go to brand now." },
  { id: 24, name: "Eshaal Hussain", city: "Faisalabad", rating: 5, review: "Received the printed t-shirt pack earlier than expected, packaging was neat too. Highly recommend to all the moms out there." },
  { id: 25, name: "Adnan Awan", city: "Karachi", rating: 5, review: "the ethnic wear set for Eid exceeded my expectations, honestly. Colors were exactly as shown on the website." },
  { id: 26, name: "Warda Raza", city: "Lahore", rating: 4, review: "My son looks adorable in the winter fleece jacket, so happy with the purchase. Delivery to Lahore was quick too." },
  { id: 27, name: "Ahmed Sultan", city: "Gujrat", rating: 4, review: "the cotton kurta set exceeded my expectations, honestly. Already planning my next order." },
  { id: 28, name: "Junaid Abbasi", city: "Islamabad", rating: 5, review: "My daughter can't stop wearing the pastel abaya set, she loves it so much. Highly recommend to all the moms out there." },
  { id: 29, name: "Zeeshan Iqbal", city: "Sialkot", rating: 4, review: "The fabric quality on the eid collection outfit is top notch, very soft on the skin. Already planning my next order." },
  { id: 30, name: "Nauman Javed", city: "Islamabad", rating: 4, review: "the eid collection outfit is good value for money, nothing extraordinary but does the job. Decent purchase, will consider ordering again." },
  { id: 31, name: "Waqas Latif", city: "Sialkot", rating: 5, review: "Just Kiddin' never disappoints, the ethnic wear set for Eid was perfect. Highly recommend to all the moms out there." },
  { id: 32, name: "Areeba Chaudhry", city: "Faisalabad", rating: 4, review: "Stitching on the newborn onesies is really neat, no loose threads at all. Delivery to Faisalabad was quick too." },
  { id: 33, name: "Yousuf Sheikh", city: "Multan", rating: 4, review: "Fabric of the printed t-shirt pack is comfortable, packaging could be better though. Good enough for the price point." },
  { id: 34, name: "Zain Chughtai", city: "Karachi", rating: 4, review: "Absolutely loved the cotton nightwear set I ordered for my kid. Already planning my next order." },
  { id: 35, name: "Shayan Gill", city: "Lahore", rating: 4, review: "The fabric quality on the winter fleece jacket is top notch, very soft on the skin. Sizing was accurate as per the chart given." },
  { id: 36, name: "Minahil Baig", city: "Multan", rating: 4, review: "Happy with the baby sleepsuit overall, just wish there were more color options. Customer support responded a bit late but resolved my issue." },
  { id: 37, name: "Iqra Ansari", city: "Karachi", rating: 5, review: "the cargo shorts set exceeded my expectations, honestly. Already planning my next order." },
  { id: 38, name: "Adeel Bajwa", city: "Lahore", rating: 4, review: "Happy with the party wear dress overall, just wish there were more color options. Would recommend with slight reservations about sizing." },
  { id: 39, name: "Ayesha Qureshi", city: "Faisalabad", rating: 4, review: "the jeans jacket combo fits well, stitching is okay, would still recommend. Customer support responded a bit late but resolved my issue." },
  { id: 40, name: "Mehak Aslam", city: "Rawalpindi", rating: 5, review: "Ordered the cotton kurta set and the quality is amazing for the price. Five stars from me and my little one." },
  { id: 41, name: "Zainab Tarar", city: "Karachi", rating: 5, review: "the cargo shorts set exceeded my expectations, honestly. Colors were exactly as shown on the website." },
  { id: 42, name: "Ayesha Kiani", city: "Rawalpindi", rating: 5, review: "Just Kiddin' never disappoints, the eid collection outfit was perfect. Delivery to Rawalpindi was quick too." },
  { id: 43, name: "Hussain Sheikh", city: "Sialkot", rating: 4, review: "Happy with the boys polo shirts overall, just wish there were more color options. Still satisfied with the purchase overall." },
  { id: 44, name: "Sundas Raza", city: "Lahore", rating: 5, review: "The fabric quality on the denim dungarees is top notch, very soft on the skin. Already planning my next order." },
  { id: 45, name: "Anaya Gill", city: "Sargodha", rating: 5, review: "the summer romper set exceeded my expectations, honestly. Customer service was also very helpful throughout." },
  { id: 46, name: "Abdullah Qureshi", city: "Karachi", rating: 3, review: "the boys polo shirts is nice but the size ran slightly small for my son. Still satisfied with the purchase overall." },
  { id: 47, name: "Salman Kiani", city: "Sargodha", rating: 5, review: "Stitching on the eid collection outfit is really neat, no loose threads at all. Worth every rupee spent." },
  { id: 48, name: "Yousuf Aslam", city: "Multan", rating: 5, review: "Absolutely loved the striped hoodie I ordered for my kid. Highly recommend to all the moms out there." },
  { id: 49, name: "Sidra Hussain", city: "Faisalabad", rating: 5, review: "Received the eid collection outfit earlier than expected, packaging was neat too. Will definitely order again soon." },
  { id: 50, name: "Danish Warraich", city: "Gujrat", rating: 4, review: "the cotton nightwear set is good value for money, nothing extraordinary but does the job. Good enough for the price point." },
  { id: 51, name: "Hira Niazi", city: "Islamabad", rating: 5, review: "My son looks adorable in the printed t-shirt pack, so happy with the purchase. Sizing was accurate as per the chart given." },
  { id: 52, name: "Hania Niazi", city: "Karachi", rating: 4, review: "the pastel abaya set is decent overall, my kid likes it. Still satisfied with the purchase overall." },
  { id: 53, name: "Shahzaib Chughtai", city: "Karachi", rating: 4, review: "Received the newborn onesies earlier than expected, packaging was neat too. Worth every rupee spent." },
  { id: 54, name: "Junaid Mirza", city: "Karachi", rating: 4, review: "Ordered the winter fleece jacket, quality is fine but color was a little different from the picture. Not perfect but definitely worth trying." },
  { id: 55, name: "Sana Khan", city: "Karachi", rating: 5, review: "Stitching on the striped hoodie is really neat, no loose threads at all. Already planning my next order." },
  { id: 56, name: "Alishba Farooq", city: "Faisalabad", rating: 3, review: "Good quality the school uniform bundle, though delivery took a bit longer than expected. Decent purchase, will consider ordering again." },
  { id: 57, name: "Hassan Mirza", city: "Gujranwala", rating: 4, review: "My son looks adorable in the corduroy pants, so happy with the purchase. Customer service was also very helpful throughout." },
  { id: 58, name: "Nimra Aslam", city: "Islamabad", rating: 3, review: "the striped hoodie is nice but the size ran slightly small for my son. Good enough for the price point." },
  { id: 59, name: "Imran Warraich", city: "Gujrat", rating: 5, review: "the boys polo shirts exceeded my expectations, honestly. Five stars from me and my little one." },
  { id: 60, name: "Hafsa Khan", city: "Lahore", rating: 4, review: "My daughter can't stop wearing the cotton kurta set, she loves it so much. Five stars from me and my little one." },
  { id: 61, name: "Waleed Cheema", city: "Multan", rating: 3, review: "Good quality the cotton kurta set, though delivery took a bit longer than expected. Would order again but hoping for faster delivery next time." },
  { id: 62, name: "Tania Malik", city: "Gujrat", rating: 5, review: "My son looks adorable in the boys polo shirts, so happy with the purchase. Customer service was also very helpful throughout." },
  { id: 63, name: "Ali Abbasi", city: "Multan", rating: 4, review: "My son looks adorable in the eid collection outfit, so happy with the purchase. Highly recommend to all the moms out there." },
  { id: 64, name: "Zeeshan Raza", city: "Gujrat", rating: 3, review: "the summer romper set is decent overall, my kid likes it. Would recommend with slight reservations about sizing." },
  { id: 65, name: "Abdullah Javed", city: "Faisalabad", rating: 4, review: "Ordered the printed t-shirt pack and the quality is amazing for the price. Customer service was also very helpful throughout." },
  { id: 66, name: "Noman Sultan", city: "Multan", rating: 5, review: "This is my third order from Just Kiddin' and the ethnic wear set for Eid was the best yet. Colors were exactly as shown on the website." },
  { id: 67, name: "Shaista Malik", city: "Gujrat", rating: 4, review: "Absolutely loved the cotton nightwear set I ordered for my kid. Sizing was accurate as per the chart given." },
  { id: 68, name: "Junaid Baig", city: "Sialkot", rating: 5, review: "My daughter can't stop wearing the boys polo shirts, she loves it so much. Sizing was accurate as per the chart given." },
  { id: 69, name: "Anaya Ansari", city: "Multan", rating: 4, review: "This is my third order from Just Kiddin' and the floral summer dress was the best yet. Worth every rupee spent." },
  { id: 70, name: "Fatima Aslam", city: "Faisalabad", rating: 4, review: "Happy with the party wear dress overall, just wish there were more color options. Would order again but hoping for faster delivery next time." },
  { id: 71, name: "Imran Rashid", city: "Gujrat", rating: 3, review: "Good quality the eid collection outfit, though delivery took a bit longer than expected. Would order again but hoping for faster delivery next time." },
  { id: 72, name: "Sana Mirza", city: "Sialkot", rating: 5, review: "Ordered the school uniform bundle and the quality is amazing for the price. Highly recommend to all the moms out there." },
  { id: 73, name: "Kinza Warraich", city: "Karachi", rating: 4, review: "Just Kiddin' never disappoints, the corduroy pants was perfect. Colors were exactly as shown on the website." },
  { id: 74, name: "Umair Sultan", city: "Multan", rating: 5, review: "The fabric quality on the girls frock is top notch, very soft on the skin. Worth every rupee spent." },
  { id: 75, name: "Zeeshan Butt", city: "Rawalpindi", rating: 4, review: "My daughter can't stop wearing the denim dungarees, she loves it so much. Five stars from me and my little one." },
  { id: 76, name: "Eshaal Tarar", city: "Sialkot", rating: 5, review: "This is my third order from Just Kiddin' and the cotton kurta set was the best yet. Customer service was also very helpful throughout." },
  { id: 77, name: "Fatima Sultan", city: "Lahore", rating: 3, review: "the party wear dress is nice but the size ran slightly small for my son. Would order again but hoping for faster delivery next time." },
  { id: 78, name: "Aftab Kiani", city: "Rawalpindi", rating: 5, review: "This is my third order from Just Kiddin' and the cargo shorts set was the best yet. Already planning my next order." },
  { id: 79, name: "Yousuf Qureshi", city: "Karachi", rating: 5, review: "This is my third order from Just Kiddin' and the pastel abaya set was the best yet. Five stars from me and my little one." },
  { id: 80, name: "Sidra Warraich", city: "Karachi", rating: 3, review: "the pastel abaya set is decent overall, my kid likes it. Would recommend with slight reservations about sizing." },
  { id: 81, name: "Zain Kiani", city: "Islamabad", rating: 3, review: "the ethnic wear set for Eid is good value for money, nothing extraordinary but does the job. Overall a good experience, minor issues aside." },
  { id: 82, name: "Saba Tarar", city: "Karachi", rating: 3, review: "Fabric of the ethnic wear set for Eid is comfortable, packaging could be better though. Decent purchase, will consider ordering again." },
  { id: 83, name: "Ahmed Gill", city: "Faisalabad", rating: 3, review: "Good quality the denim dungarees, though delivery took a bit longer than expected. Good enough for the price point." },
  { id: 84, name: "Faizan Khan", city: "Sargodha", rating: 4, review: "Ordered the girls frock and the quality is amazing for the price. Will definitely order again soon." },
  { id: 85, name: "Nimra Chaudhry", city: "Lahore", rating: 4, review: "Received the baby sleepsuit earlier than expected, packaging was neat too. Highly recommend to all the moms out there." },
  { id: 86, name: "Kinza Mirza", city: "Sargodha", rating: 3, review: "Good quality the corduroy pants, though delivery took a bit longer than expected. Not perfect but definitely worth trying." },
  { id: 87, name: "Bilal Abbasi", city: "Gujrat", rating: 5, review: "The fabric quality on the school uniform bundle is top notch, very soft on the skin. Highly recommend to all the moms out there." },
  { id: 88, name: "Yusra Qureshi", city: "Rawalpindi", rating: 5, review: "the cargo shorts set exceeded my expectations, honestly. Will definitely order again soon." },
  { id: 89, name: "Rida Sultan", city: "Lahore", rating: 5, review: "My daughter can't stop wearing the cotton nightwear set, she loves it so much. Delivery to Lahore was quick too." },
  { id: 90, name: "Imran Cheema", city: "Multan", rating: 5, review: "This is my third order from Just Kiddin' and the floral summer dress was the best yet. Just Kiddin' has become our go to brand now." },
  { id: 91, name: "Zain Awan", city: "Multan", rating: 4, review: "Ordered the cotton nightwear set and the quality is amazing for the price. Just Kiddin' has become our go to brand now." },
  { id: 92, name: "Saad Ansari", city: "Gujrat", rating: 5, review: "the summer romper set exceeded my expectations, honestly. Colors were exactly as shown on the website." },
  { id: 93, name: "Javeria Raza", city: "Sialkot", rating: 5, review: "Ordered the school uniform bundle and the quality is amazing for the price. Five stars from me and my little one." },
  { id: 94, name: "Haris Siddiqui", city: "Gujranwala", rating: 5, review: "Ordered the printed t-shirt pack and the quality is amazing for the price. Customer service was also very helpful throughout." },
  { id: 95, name: "Hira Rashid", city: "Multan", rating: 3, review: "the summer romper set is nice but the size ran slightly small for my son. Good enough for the price point." },
  { id: 96, name: "Tania Sultan", city: "Sargodha", rating: 4, review: "Fabric of the party wear dress is comfortable, packaging could be better though. Would order again but hoping for faster delivery next time." },
  { id: 97, name: "Waleed Ansari", city: "Sargodha", rating: 4, review: "The fabric quality on the girls frock is top notch, very soft on the skin. Worth every rupee spent." },
  { id: 98, name: "Areeba Butt", city: "Islamabad", rating: 4, review: "This is my third order from Just Kiddin' and the denim dungarees was the best yet. Just Kiddin' has become our go to brand now." },
  { id: 99, name: "Yusra Rashid", city: "Sialkot", rating: 5, review: "This is my third order from Just Kiddin' and the eid collection outfit was the best yet. Sizing was accurate as per the chart given." },
  { id: 100, name: "Shaista Kiani", city: "Sialkot", rating: 4, review: "the boys polo shirts exceeded my expectations, honestly. Colors were exactly as shown on the website." },
  { id: 101, name: "Aiman Javed", city: "Faisalabad", rating: 4, review: "Ordered the striped hoodie, quality is fine but color was a little different from the picture. Still satisfied with the purchase overall." },
  { id: 102, name: "Anum Sheikh", city: "Rawalpindi", rating: 5, review: "the corduroy pants exceeded my expectations, honestly. Customer service was also very helpful throughout." },
  { id: 103, name: "Aiman Tarar", city: "Lahore", rating: 5, review: "Ordered the baby sleepsuit and the quality is amazing for the price. Already planning my next order." },
  { id: 104, name: "Haris Chaudhry", city: "Gujrat", rating: 4, review: "Stitching on the denim dungarees is really neat, no loose threads at all. Just Kiddin' has become our go to brand now." },
  { id: 105, name: "Moiz Siddiqui", city: "Karachi", rating: 5, review: "the corduroy pants exceeded my expectations, honestly. Five stars from me and my little one." },
  { id: 106, name: "Fatima Dogar", city: "Faisalabad", rating: 5, review: "Ordered the denim dungarees and the quality is amazing for the price. Sizing was accurate as per the chart given." },
  { id: 107, name: "Anum Qureshi", city: "Karachi", rating: 5, review: "The fabric quality on the party wear dress is top notch, very soft on the skin. Delivery to Karachi was quick too." },
  { id: 108, name: "Rimsha Khan", city: "Islamabad", rating: 4, review: "Just Kiddin' never disappoints, the baby sleepsuit was perfect. Delivery to Islamabad was quick too." },
  { id: 109, name: "Junaid Malik", city: "Islamabad", rating: 4, review: "the floral summer dress is good value for money, nothing extraordinary but does the job. Decent purchase, will consider ordering again." },
  { id: 110, name: "Noman Farooq", city: "Karachi", rating: 5, review: "This is my third order from Just Kiddin' and the cotton nightwear set was the best yet. Just Kiddin' has become our go to brand now." },
  { id: 111, name: "Farhan Kiani", city: "Sialkot", rating: 3, review: "Good quality the floral summer dress, though delivery took a bit longer than expected. Decent purchase, will consider ordering again." },
  { id: 112, name: "Waqas Gill", city: "Faisalabad", rating: 4, review: "Just Kiddin' never disappoints, the striped hoodie was perfect. Highly recommend to all the moms out there." },
  { id: 113, name: "Basit Ansari", city: "Karachi", rating: 5, review: "The fabric quality on the jeans jacket combo is top notch, very soft on the skin. Sizing was accurate as per the chart given." },
  { id: 114, name: "Anum Latif", city: "Lahore", rating: 5, review: "This is my third order from Just Kiddin' and the printed t-shirt pack was the best yet. Just Kiddin' has become our go to brand now." },
  { id: 115, name: "Kinza Ansari", city: "Sargodha", rating: 3, review: "the school uniform bundle is nice but the size ran slightly small for my son. Decent purchase, will consider ordering again." },
  { id: 116, name: "Imran Baig", city: "Sialkot", rating: 5, review: "Ordered the baby sleepsuit and the quality is amazing for the price. Colors were exactly as shown on the website." },
  { id: 117, name: "Rabia Hussain", city: "Islamabad", rating: 5, review: "Just Kiddin' never disappoints, the striped hoodie was perfect. Delivery to Islamabad was quick too." },
  { id: 118, name: "Umair Chaudhry", city: "Gujranwala", rating: 5, review: "My son looks adorable in the pastel abaya set, so happy with the purchase. Customer service was also very helpful throughout." },
  { id: 119, name: "Manahil Sheikh", city: "Rawalpindi", rating: 5, review: "This is my third order from Just Kiddin' and the denim dungarees was the best yet. Five stars from me and my little one." },
  { id: 120, name: "Abdullah Bajwa", city: "Sargodha", rating: 5, review: "My daughter can't stop wearing the cargo shorts set, she loves it so much. Customer service was also very helpful throughout." },
  { id: 121, name: "Iqra Sheikh", city: "Multan", rating: 4, review: "the denim dungarees exceeded my expectations, honestly. Already planning my next order." },
  { id: 122, name: "Waqas Aslam", city: "Islamabad", rating: 5, review: "My daughter can't stop wearing the cotton nightwear set, she loves it so much. Just Kiddin' has become our go to brand now." },
  { id: 123, name: "Sohail Butt", city: "Gujranwala", rating: 4, review: "My son looks adorable in the summer romper set, so happy with the purchase. Customer service was also very helpful throughout." },
  { id: 124, name: "Aqsa Farooq", city: "Sialkot", rating: 3, review: "Fabric of the boys polo shirts is comfortable, packaging could be better though. Decent purchase, will consider ordering again." },
  { id: 125, name: "Tania Cheema", city: "Islamabad", rating: 5, review: "Received the girls frock earlier than expected, packaging was neat too. Highly recommend to all the moms out there." },
  { id: 126, name: "Bilal Rashid", city: "Gujrat", rating: 5, review: "My son looks adorable in the eid collection outfit, so happy with the purchase. Five stars from me and my little one." },
  { id: 127, name: "Rabia Aslam", city: "Multan", rating: 5, review: "My daughter can't stop wearing the party wear dress, she loves it so much. Will definitely order again soon." },
  { id: 128, name: "Areeba Malik", city: "Islamabad", rating: 5, review: "Stitching on the cargo shorts set is really neat, no loose threads at all. Highly recommend to all the moms out there." },
  { id: 129, name: "Waqas Niazi", city: "Sargodha", rating: 5, review: "the printed t-shirt pack exceeded my expectations, honestly. Worth every rupee spent." },
  { id: 130, name: "Aiman Baig", city: "Rawalpindi", rating: 3, review: "the ethnic wear set for Eid is decent overall, my kid likes it. Not perfect but definitely worth trying." },
  { id: 131, name: "Momina Sultan", city: "Sialkot", rating: 5, review: "Received the school uniform bundle earlier than expected, packaging was neat too. Colors were exactly as shown on the website." },
  { id: 132, name: "Hassan Ansari", city: "Karachi", rating: 5, review: "My son looks adorable in the baby sleepsuit, so happy with the purchase. Highly recommend to all the moms out there." },
  { id: 133, name: "Ayesha Baig", city: "Rawalpindi", rating: 5, review: "My daughter can't stop wearing the pastel abaya set, she loves it so much. Already planning my next order." },
  { id: 134, name: "Zara Bajwa", city: "Islamabad", rating: 5, review: "Received the newborn onesies earlier than expected, packaging was neat too. Colors were exactly as shown on the website." },
  { id: 135, name: "Adeel Sultan", city: "Gujrat", rating: 5, review: "The fabric quality on the school uniform bundle is top notch, very soft on the skin. Already planning my next order." },
  { id: 136, name: "Asad Butt", city: "Gujrat", rating: 5, review: "The fabric quality on the winter fleece jacket is top notch, very soft on the skin. Sizing was accurate as per the chart given." },
  { id: 137, name: "Farwa Rashid", city: "Rawalpindi", rating: 4, review: "Ordered the cotton kurta set, quality is fine but color was a little different from the picture. Good enough for the price point." },
  { id: 138, name: "Mahnoor Iqbal", city: "Karachi", rating: 5, review: "Stitching on the newborn onesies is really neat, no loose threads at all. Just Kiddin' has become our go to brand now." },
  { id: 139, name: "Huzaifa Qureshi", city: "Karachi", rating: 5, review: "Received the corduroy pants earlier than expected, packaging was neat too. Five stars from me and my little one." },
  { id: 140, name: "Bilal Baig", city: "Faisalabad", rating: 4, review: "Ordered the ethnic wear set for Eid and the quality is amazing for the price. Five stars from me and my little one." },
  { id: 141, name: "Adeel Malik", city: "Islamabad", rating: 4, review: "The fabric quality on the eid collection outfit is top notch, very soft on the skin. Just Kiddin' has become our go to brand now." },
  { id: 142, name: "Emaan Hussain", city: "Islamabad", rating: 5, review: "Just Kiddin' never disappoints, the cotton kurta set was perfect. Will definitely order again soon." },
  { id: 143, name: "Rehan Cheema", city: "Faisalabad", rating: 5, review: "the girls frock exceeded my expectations, honestly. Will definitely order again soon." },
  { id: 144, name: "Tania Sheikh", city: "Rawalpindi", rating: 4, review: "the boys polo shirts is decent overall, my kid likes it. Not perfect but definitely worth trying." },
  { id: 145, name: "Mahnoor Dogar", city: "Islamabad", rating: 4, review: "Happy with the jeans jacket combo overall, just wish there were more color options. Overall a good experience, minor issues aside." },
  { id: 146, name: "Saba Abbasi", city: "Sargodha", rating: 5, review: "Received the cargo shorts set earlier than expected, packaging was neat too. Colors were exactly as shown on the website." },
  { id: 147, name: "Zara Aslam", city: "Sialkot", rating: 4, review: "Happy with the party wear dress overall, just wish there were more color options. Decent purchase, will consider ordering again." },
  { id: 148, name: "Hafsa Kiani", city: "Karachi", rating: 5, review: "Stitching on the ethnic wear set for Eid is really neat, no loose threads at all. Just Kiddin' has become our go to brand now." },
  { id: 149, name: "Noman Javed", city: "Gujrat", rating: 4, review: "The fabric quality on the ethnic wear set for Eid is top notch, very soft on the skin. Sizing was accurate as per the chart given." },
  { id: 150, name: "Rimsha Farooq", city: "Islamabad", rating: 5, review: "Stitching on the printed t-shirt pack is really neat, no loose threads at all. Sizing was accurate as per the chart given." },
  { id: 151, name: "Dua Siddiqui", city: "Faisalabad", rating: 3, review: "Good quality the newborn onesies, though delivery took a bit longer than expected. Still satisfied with the purchase overall." },
  { id: 152, name: "Ibrahim Sultan", city: "Sargodha", rating: 5, review: "Just Kiddin' never disappoints, the pastel abaya set was perfect. Highly recommend to all the moms out there." },
  { id: 153, name: "Umair Dogar", city: "Sargodha", rating: 5, review: "Just Kiddin' never disappoints, the denim dungarees was perfect. Will definitely order again soon." },
  { id: 154, name: "Fatima Cheema", city: "Islamabad", rating: 4, review: "the baby sleepsuit is good value for money, nothing extraordinary but does the job. Would order again but hoping for faster delivery next time." },
  { id: 155, name: "Junaid Aslam", city: "Multan", rating: 5, review: "The fabric quality on the school uniform bundle is top notch, very soft on the skin. Will definitely order again soon." },
  { id: 156, name: "Eshaal Abbasi", city: "Sialkot", rating: 5, review: "Ordered the baby sleepsuit and the quality is amazing for the price. Highly recommend to all the moms out there." },
  { id: 157, name: "Nauman Awan", city: "Multan", rating: 5, review: "Ordered the summer romper set and the quality is amazing for the price. Five stars from me and my little one." },
  { id: 158, name: "Eshaal Cheema", city: "Sargodha", rating: 4, review: "the jeans jacket combo is good value for money, nothing extraordinary but does the job. Would order again but hoping for faster delivery next time." },
  { id: 159, name: "Tayyab Chaudhry", city: "Rawalpindi", rating: 4, review: "Ordered the cargo shorts set, quality is fine but color was a little different from the picture. Not perfect but definitely worth trying." },
  { id: 160, name: "Sana Bajwa", city: "Multan", rating: 5, review: "Ordered the striped hoodie and the quality is amazing for the price. Customer service was also very helpful throughout." },
  { id: 161, name: "Dua Abbasi", city: "Gujrat", rating: 3, review: "Good quality the school uniform bundle, though delivery took a bit longer than expected. Overall a good experience, minor issues aside." },
  { id: 162, name: "Tayyab Awan", city: "Gujranwala", rating: 5, review: "The fabric quality on the pastel abaya set is top notch, very soft on the skin. Sizing was accurate as per the chart given." },
  { id: 163, name: "Arsalan Khan", city: "Karachi", rating: 5, review: "Received the pastel abaya set earlier than expected, packaging was neat too. Delivery to Karachi was quick too." },
  { id: 164, name: "Taha Raza", city: "Lahore", rating: 5, review: "The fabric quality on the eid collection outfit is top notch, very soft on the skin. Sizing was accurate as per the chart given." },
  { id: 165, name: "Ammar Raza", city: "Sialkot", rating: 5, review: "This is my third order from Just Kiddin' and the boys polo shirts was the best yet. Worth every rupee spent." },
  { id: 166, name: "Owais Tarar", city: "Islamabad", rating: 5, review: "Ordered the cotton kurta set and the quality is amazing for the price. Already planning my next order." },
  { id: 167, name: "Sarah Aslam", city: "Gujranwala", rating: 5, review: "Absolutely loved the cotton nightwear set I ordered for my kid. Sizing was accurate as per the chart given." },
  { id: 168, name: "Hamza Sultan", city: "Gujranwala", rating: 4, review: "The fabric quality on the cotton kurta set is top notch, very soft on the skin. Delivery to Gujranwala was quick too." },
  { id: 169, name: "Aiman Chughtai", city: "Gujrat", rating: 4, review: "Absolutely loved the jeans jacket combo I ordered for my kid. Delivery to Gujrat was quick too." },
  { id: 170, name: "Wardah Mirza", city: "Rawalpindi", rating: 5, review: "This is my third order from Just Kiddin' and the cotton nightwear set was the best yet. Will definitely order again soon." },
  { id: 171, name: "Bilal Malik", city: "Rawalpindi", rating: 4, review: "Good quality the eid collection outfit, though delivery took a bit longer than expected. Would order again but hoping for faster delivery next time." },
  { id: 172, name: "Naila Awan", city: "Lahore", rating: 4, review: "the striped hoodie is good value for money, nothing extraordinary but does the job. Not perfect but definitely worth trying." },
  { id: 173, name: "Saba Malik", city: "Sargodha", rating: 3, review: "the printed t-shirt pack fits well, stitching is okay, would still recommend. Still satisfied with the purchase overall." },
  { id: 174, name: "Noor Rashid", city: "Multan", rating: 5, review: "Absolutely loved the cotton kurta set I ordered for my kid. Highly recommend to all the moms out there." },
  { id: 175, name: "Kinza Dogar", city: "Faisalabad", rating: 4, review: "the ethnic wear set for Eid exceeded my expectations, honestly. Just Kiddin' has become our go to brand now." },
  { id: 176, name: "Nimra Tarar", city: "Karachi", rating: 4, review: "Good quality the eid collection outfit, though delivery took a bit longer than expected. Decent purchase, will consider ordering again." },
  { id: 177, name: "Yusra Khan", city: "Sargodha", rating: 3, review: "Good quality the eid collection outfit, though delivery took a bit longer than expected. Overall a good experience, minor issues aside." },
  { id: 178, name: "Ali Raza", city: "Islamabad", rating: 5, review: "Received the cotton nightwear set earlier than expected, packaging was neat too. Worth every rupee spent." },
  { id: 179, name: "Zainab Mirza", city: "Islamabad", rating: 3, review: "the jeans jacket combo is good value for money, nothing extraordinary but does the job. Still satisfied with the purchase overall." },
  { id: 180, name: "Shaheer Chaudhry", city: "Sargodha", rating: 4, review: "Stitching on the cotton kurta set is really neat, no loose threads at all. Colors were exactly as shown on the website." },
  { id: 181, name: "Aftab Ansari", city: "Karachi", rating: 5, review: "Absolutely loved the cargo shorts set I ordered for my kid. Sizing was accurate as per the chart given." },
  { id: 182, name: "Naila Butt", city: "Rawalpindi", rating: 5, review: "My son looks adorable in the girls frock, so happy with the purchase. Colors were exactly as shown on the website." },
  { id: 183, name: "Ali Cheema", city: "Gujranwala", rating: 5, review: "The fabric quality on the boys polo shirts is top notch, very soft on the skin. Customer service was also very helpful throughout." },
  { id: 184, name: "Asad Javed", city: "Islamabad", rating: 4, review: "Good quality the corduroy pants, though delivery took a bit longer than expected. Would recommend with slight reservations about sizing." },
  { id: 185, name: "Ayesha Rashid", city: "Sargodha", rating: 4, review: "Just Kiddin' never disappoints, the school uniform bundle was perfect. Colors were exactly as shown on the website." },
  { id: 186, name: "Tania Butt", city: "Karachi", rating: 5, review: "Stitching on the jeans jacket combo is really neat, no loose threads at all. Five stars from me and my little one." },
  { id: 187, name: "Zara Chaudhry", city: "Karachi", rating: 5, review: "This is my third order from Just Kiddin' and the cotton kurta set was the best yet. Delivery to Karachi was quick too." },
  { id: 188, name: "Fahad Sultan", city: "Gujrat", rating: 5, review: "Ordered the school uniform bundle and the quality is amazing for the price. Will definitely order again soon." },
  { id: 189, name: "Imran Mirza", city: "Sargodha", rating: 3, review: "the eid collection outfit is nice but the size ran slightly small for my son. Good enough for the price point." },
  { id: 190, name: "Eshaal Ansari", city: "Sialkot", rating: 4, review: "Good quality the girls frock, though delivery took a bit longer than expected. Not perfect but definitely worth trying." },
  { id: 191, name: "Shayan Tarar", city: "Sargodha", rating: 3, review: "the baby sleepsuit is good value for money, nothing extraordinary but does the job. Decent purchase, will consider ordering again." },
  { id: 192, name: "Salman Tarar", city: "Sialkot", rating: 5, review: "Ordered the ethnic wear set for Eid and the quality is amazing for the price. Will definitely order again soon." },
  { id: 193, name: "Aftab Malik", city: "Islamabad", rating: 4, review: "the pastel abaya set is nice but the size ran slightly small for my son. Not perfect but definitely worth trying." },
  { id: 194, name: "Kinza Hussain", city: "Karachi", rating: 4, review: "the jeans jacket combo is good value for money, nothing extraordinary but does the job. Not perfect but definitely worth trying." },
  { id: 195, name: "Zainab Sheikh", city: "Sargodha", rating: 4, review: "the boys polo shirts fits well, stitching is okay, would still recommend. Would recommend with slight reservations about sizing." },
  { id: 196, name: "Aftab Gill", city: "Lahore", rating: 3, review: "the striped hoodie is nice but the size ran slightly small for my son. Not perfect but definitely worth trying." },
  { id: 197, name: "Ayla Iqbal", city: "Gujrat", rating: 3, review: "the newborn onesies is nice but the size ran slightly small for my son. Customer support responded a bit late but resolved my issue." },
  { id: 198, name: "Nauman Chaudhry", city: "Sialkot", rating: 3, review: "the girls frock is decent overall, my kid likes it. Would recommend with slight reservations about sizing." },
  { id: 199, name: "Abdullah Aslam", city: "Lahore", rating: 4, review: "Fabric of the summer romper set is comfortable, packaging could be better though. Customer support responded a bit late but resolved my issue." },
  { id: 200, name: "Komal Tarar", city: "Sialkot", rating: 5, review: "Received the newborn onesies earlier than expected, packaging was neat too. Customer service was also very helpful throughout." },
];